name: Release Scheduler
#on:
#  schedule:
#    - cron: "5 * * * *"
on:
  workflow_dispatch:
  
jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout branch "main"
        uses: actions/checkout@v2
        with:
          ref: 'main'
      - name: Tag snapshot
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.date.outputs.date }}
