name: Release Scheduler
#on:
#  schedule:
#    - cron: "5 * * * *"
on:
  workflow_dispatch:
  
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: 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 # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
